# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '123.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1067, 796)
        self.widget_2 = QtWidgets.QWidget(widget)
        self.widget_2.setGeometry(QtCore.QRect(260, 90, 721, 80))
        self.widget_2.setObjectName("widget_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(220, 30, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.widget_3 = QtWidgets.QWidget(widget)
        self.widget_3.setGeometry(QtCore.QRect(160, 480, 821, 80))
        self.widget_3.setObjectName("widget_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 10, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox = QtWidgets.QComboBox(widget)
        self.comboBox.setGeometry(QtCore.QRect(270, 270, 87, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "投促中心报销软件应用"))
        self.pushButton.setText(_translate("widget", "123"))
        self.pushButton_2.setText(_translate("widget", "456"))
        self.comboBox.setItemText(0, _translate("widget", "1"))
        self.comboBox.setItemText(1, _translate("widget", "2"))
        self.comboBox.setItemText(2, _translate("widget", "3"))
