# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'outlook.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1067, 762)
        self.Title = QtWidgets.QLabel(widget)
        self.Title.setGeometry(QtCore.QRect(360, 0, 381, 61))
        font = QtGui.QFont()
        font.setFamily("方正小标宋_GBK")
        font.setPointSize(20)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.comboBox = QtWidgets.QComboBox(widget)
        self.comboBox.setGeometry(QtCore.QRect(120, 50, 111, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label1 = QtWidgets.QLabel(widget)
        self.label1.setGeometry(QtCore.QRect(30, 50, 81, 21))
        self.label1.setObjectName("label1")
        self.dateEdit = QtWidgets.QDateEdit(widget)
        self.dateEdit.setGeometry(QtCore.QRect(160, 170, 110, 22))
        self.dateEdit.setObjectName("dateEdit")
        self.label2 = QtWidgets.QLabel(widget)
        self.label2.setGeometry(QtCore.QRect(50, 170, 81, 21))
        self.label2.setObjectName("label2")
        self.Sure = QtWidgets.QPushButton(widget)
        self.Sure.setGeometry(QtCore.QRect(380, 600, 93, 28))
        self.Sure.setObjectName("Sure")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "投促中心报销软件应用"))
        self.Title.setText(_translate("widget", "投促中心报销软件应用"))
        self.comboBox.setItemText(0, _translate("widget", "要填的"))
        self.comboBox.setItemText(1, _translate("widget", "招待用餐"))
        self.comboBox.setItemText(2, _translate("widget", "市外出行"))
        self.comboBox.setItemText(3, _translate("widget", "市内出行"))
        self.comboBox.setItemText(4, _translate("widget", "市外出行 + 招待用餐"))
        self.comboBox.setItemText(5, _translate("widget", "市内出行 + 招待用餐"))
        self.label1.setText(_translate("widget", "报销事项"))
        self.label2.setText(_translate("widget", "报销时间"))
        self.Sure.setText(_translate("widget", "OK"))
